.TH "Arduino/libraries/uSpeech/uSpeech Directory Reference" 3 "Sat Jan 25 2014" "Version 4.1.2" "µSpeech" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arduino/libraries/uSpeech/uSpeech Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBphoneme\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsignal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBuspeech\&.h\fP"
.br
.ti -1c
.RI "file \fBvocab\&.cpp\fP"
.br
.in -1c
